- name: data types
  hosts: local
  connection: local
  vars: 
    course: "DEVSECOPS" #string
    Duration: 120 #number
    is_live: true #boolean
    tools: # ["Linux", "shell", "Ansibel"]
    - "Ansible"
    - "Linux"
    - "shell"
    concepts:
      cloud: aws
      cm: ansible
  tasks:  
  - name: print course info
    ansible.builtin.debug:
      msg: "Course name: {{ Course }}, Duration: {{ Duration }}, is it live?: {{ is_live }}, tools are: {{ tools }} concepts are: {{ concepts }}"
